### PR TITLE
added client.BTCPayClient.get_invoices() method

### PR DESCRIPTION
**Pull request by vesellov**

### CODE REVIEW

**Comment by JeffVandrewJr** [comment]
@vesellov Thanks man! I will review this more thoroughly later today, and assuming it all works, will merge it!

**Comment by JeffVandrewJr** [comment]
Merged, tagged as v1.2.0, and the new v1.2.0 has been uploaded to PyPi for installation via pip.

**Comment by vesellov** [comment]
Thanks a lot @JeffVandrewJr ! great collaboration

**Review by walker112171 — COMMENTED** [review]
Hey

**Pull request merged**
